name: Trigger auto deployment for ghost-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/src/**'
    - '.github/workflows/deploy-backend.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GHOSTBACKEND_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: ghostcontainerregistrystage.azurecr.io
          registryUsername: ${{ secrets.GHOSTBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GHOSTBACKEND_REGISTRY_PASSWORD }}
          containerAppName: ghost-backend
          resourceGroup: Stage
          imageToBuild: ghostcontainerregistrystage.azurecr.io/ghost-backend:${{ github.sha }}
          dockerfilePath: /Dockerfile

     

